
[general]
import = [
	# uncomment the flavour you want below:
	# "~/.config/alacritty/catppuccin-latte.toml"
	# "~/.config/alacritty/catppuccin-frappe.toml"
	# "~/.config/alacritty/catppuccin-macchiato.toml"
	 "~/.config/alacritty/catppuccin-mocha.toml"
]
# And if on Windows: "C:/Users/${YOUR_USER_FOLDER}/AppData/Roaming/alacritty/catppuccin-mocha.toml"


# If on Windows, you may want:
# [terminal]
# shell = { program = "C:/Program Files/PowerShell/7/pwsh.exe", args = [ "-WorkingDirectory C:/Users/${YOUR_USER_FOLDER}" ] }

[window]
#padding = {x = 15, y = 15}

[env]
TERM = "xterm-256color"

[font]
# size = 7
normal = { family = "Hack Nerd Font Mono" }


[keyboard]
bindings = [
	{ key = "V", mods = "Control", action = "Paste" }, # Rebind Copy & Paste
	{ key = "C", mods = "Control", action = "Copy" },

	{ key = "C", mods = "Control|Shift", chars = "\u0003" }, # Rebind cancel

	{ key = "N", mods = "Control", action = "SpawnNewInstance"},
]
