dictionaries = [
    "en_gb",
    "en_us",
]
words = [
    "astro",
    "automations",
    "cloudflare",
    "cloudflare's",
    "cron",
    "dataverse",
    "explorable",
    "frontmatter",
    "janky",
    "jira",
    "lucide",
    "markdoc",
    "mins",
    "nmap",
    "pandoc",
    "preact",
    "signable",
    "signifiers",
    "unsplash",
    "xbox",
    "zod",
]
flag_words = ["fixme"]
ignore_patterns = [
    "[A-Z]{2,}",
    'https?://[^\s]+',
    "`[A-Za-z1-9]*`",
    '`\.[A-Za-z1-9]*`',
]
