dictionaries = [
    "en_gb",
    "en_us",
]
words = [
    "actioned",
    "astro",
    "automations",
    "catppuccin",
    "cloudflare",
    "cloudflare's",
    "cron",
    "dataverse",
    "entra",
    "explorable",
    "flatpak",
    "frontmatter",
    "fzf",
    "generalisable",
    "infographics",
    "janky",
    "jira",
    "kagi",
    "keybind",
    "keybinds",
    "lucide",
    "markdoc",
    "mins",
    "nmap",
    "nvim",
    "pandoc",
    "picotron",
    "podman",
    "portainer",
    "preact",
    "ratatui",
    "ripgrep",
    "rofi",
    "runescape",
    "sandboxed",
    "serialiser",
    "shader",
    "signable",
    "signifiers",
    "tmux",
    "unsplash",
    "xbox",
    "yazi",
    "zod",
]
flag_words = ["fixme"]
ignore_patterns = [
    "[A-Z]{2,}",
    'https?://[^\s]+',
    "`[A-Za-z1-9]*`",
    '`\.[A-Za-z1-9]*`',
]
