# yazi.toml
[manager]
show_hidden = false
linemode = "size_and_mtime"

[preview]
image_delay = 5

# https://yazi-rs.github.io/docs/configuration/keymap/

[mgr]
keymap = [
	{ on = "<C-_>", run = "hardlink", desc = "Hardlink the given folder" },
]
